name: spack-all

on:
  # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build strategy'
        type: choice
        options:
          - reuse
          - fresh
          - skip
        default: reuse

jobs:
  run:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        tool_name: [ 'radical-pilot' ]
    uses: ./.github/workflows/spack-base.yml
    with:
      tool_name: ${{ matrix.tool_name }}
      build_type: ${{ inputs.build_type || 'reuse' }}
    secrets: inherit
