name: spack-psij

on:
  # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build strategy'
        type: choice
        options:
          - reuse
          - fresh
          - skip
        default: reuse
  # https://docs.github.com/en/rest/repos/repos#create-a-repository-dispatch-event
  repository_dispatch:
    types: [ ci-spack-psij-on-demand ]
  push:
    branches: [ main ]
    paths:
      - 'ci/envs/psij/**'
      - 'ci/tests/psij/**'

jobs:
  run:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/spack-base.yml
    with:
      tool_name: psij
      build_type: ${{ github.event_name == 'push' && 'fresh' || inputs.build_type || 'reuse' }}
    secrets: inherit
